name: Install .NET SDK
description: Install current LTS and STS versions of .NET SDK.
runs:
  using: composite
  steps:
  - name: 6.0.x
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 6.0.x
  - name: 7.0.x
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 7.0.x
  - name: 8.0.x
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 8.0.x
branding:
  icon: 'umbrella'
  color: 'blue'
